version: "3"

services:

  eureka-server :
    image: eureka-server
    ports:
      - "1111:1111"
    volumes:
      - /home/Booking-Center/logs/eureka-server:/home/logs
    networks:
      - my-cloud

  feign-consumer:
    image: feign-consumer
    ports:
      - "9002:9002"
    volumes:
      - /home/Booking-Center/logs/feign-consumer:/home/logs
    networks:
      - my-cloud
    depends_on:
      - eureka-server

  api-gateway:
    image: api-gateway
    ports:
      - "5555:5555"
    volumes:
      - /home/Booking-Center/logs/api-gateway:/home/logs
    networks:
      - my-cloud
    depends_on:
      - eureka-server

  booking-service:
    image: booking-service
    ports:
      - "8080:8080"
    volumes:
      - /home/Booking-Center/logs/booking-service:/home/logs
    networks:
      - my-cloud
    depends_on:
      - eureka-server
      - api-gateway
      - feign-consumer
      - mysql
      - redis

  oauth-server:
    image: oauth-server
    ports:
      - "8090:8090"
    volumes:
      - /home/Booking-Center/logs/oauth-server:/home/logs
    networks:
      - my-cloud
    depends_on:
      - eureka-server
      - api-gateway
      - feign-consumer
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: booking_center
    volumes:
      - /home/Booking-Center/mysqlData:/var/lib/mysql
    networks:
      - my-cloud

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/Booking-Center/redisConf:/usr/local/etc/redis
      - /home/Booking-Center/redisData:/data
    command:
      redis-server
    networks:
      - my-cloud

networks:
  my-cloud:
    driver: bridge
